### PR TITLE
Migrate test framework to jest

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1201

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-spa/101)

### CODE REVIEW

**Comment by davidmason** [comment]
Reviewed 2 of 49 files at r1.
Review status: 2 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 110 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOYva6gbKcRjBBMsJE:-KLOYva6gbKcRjBBMsJF:-1462164256) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L110)):*
> ```JSON
>     "text-diff": "1.0.1"
>   },
>   "jest": {
> ```

I would prefer to have this in a different config file if we can, to keep package.json manageable. I think there is a way but it is not well documented. We should try it.

---

*[package.json, line 118 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOXdcbBHtxCIjYZQ6c:-KLOXdcc80ad89DTEOQG:2085919820) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L118)):*
> ```JSON
>       "./node_modules/fbjs",
>       "./node_modules/lodash",
>       "./src"
> ```

I just had an idea about why we are seeing the different behaviour between Travis and local builds:

Is there `src` somewhere in the full path of the `zanata-spa` directory? e.g. mine is at `/home/damason/src/zanata/zanata-spa`.

Maybe the module patterns use the full path to decide whether to exclude them, so on my local machine (and probably yours too) it would exclude everything from mocking, so basically the same as disable auto-mock.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by aeng** [comment]
Review status: 2 of 41 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 110 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOYva6gbKcRjBBMsJE:-KLOc2lPX7smYKiknf4b:-713882724) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L110)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I would prefer to have this in a different config file if we can, to keep package.json manageable. I think there is a way but it is not well documented. We should try it.
</details>
I'm not a fan of multiple config files which often brings alot of confusion without actual benefits.

---

*[package.json, line 118 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOXdcbBHtxCIjYZQ6c:-KLOci_kzcX6p9u4-Asp:466648761) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L118)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I just had an idea about why we are seeing the different behaviour between Travis and local builds:
> 
> Is there `src` somewhere in the full path of the `zanata-spa` directory? e.g. mine is at `/home/damason/src/zanata/zanata-spa`.
> 
> Maybe the module patterns use the full path to decide whether to exclude them, so on my local machine (and probably yours too) it would exclude everything from mocking, so basically the same as disable auto-mock.
</details>
Good observation. I think now with `./app`, it should do the correct exclusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by davidmason** [comment]
Reviewed 13 of 49 files at r1, 15 of 22 files at r2.
Review status: 20 of 41 files reviewed at latest revision, 7 unresolved discussions.

---

*[package.json, line 110 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOYva6gbKcRjBBMsJE:-KLOi5l6ANa39uDWE5v4:1293464025) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L110)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I'm not a fan of multiple config files which often brings alot of confusion without actual benefits.
</details>
It is a trade-off either way. I find it more of a hindrance when package.json gets full of too much stuff and it becomes hard to find things in it, but if there are a bunch of different config files it can take a while to learn where each tool is configured from - particularly if the config files have names that are different from the tool.

Usually you get some benefit from having a separate config because editors and other tools with automatically find the config and use it. This one probably isn't like that since they didn't document it well.

---

*[package.json, line 118 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOXdcbBHtxCIjYZQ6c:-KLOgn2W0gncpFeQ4QBX:1312927244) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L118)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Good observation. I think now with `./app`, it should do the correct exclusion.
</details>
ah, docs ([unmockedModulePathPatterns](https://facebook.github.io/jest/docs/api.html#unmockedmodulepathpatterns-array-string)) say that these are regexp pattern strings, so there is probably no reason to start them with `.` either.

You can override this in individual tests by specifically calling `mock()`, so maybe we should just put one or two patterns here that will match everything in the whole project. Maybe `'app'` and `'node_modules'` would be enough.

---

*[__tests__/mockAngularGettext.jsx, line 1 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOjruBkHaTxxyziyxd:-KLOjruCfM1exwF9U2w1:316413625) ([raw file](https://github.com/zanata/zanata-spa/blob/39d3ba21c03d8e4a62d8744de0524f54c9a2f3ab/__tests__/mockAngularGettext.jsx#L1)):*
> ```JSX
> import { reduce, isUndefined } from 'lodash'
> ```

While we are renaming files anyway, we might as well change them to have `.js` extension. We should only use `.jsx` if there is a file that is pure JSX with no javascript around it (I don't think we have any files like that).

---

*[__tests__/components/ButtonTest.js, line 1 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOkj8VGY9nqJrfauAd:-KLOkj8W4bdlcC9M0iXS:2190978) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/__tests__/components/ButtonTest.js#L1)):*
> ```JavaScript
> jest.disableAutomock()
> ```

We may not even need to use `disableAutomock()` if we are excluding everything from automock in the config. Maybe it is good to keep this anyway so we are certain that it is not mocking something, and it is clear when someone looks at the test file that nothing should be automatically mocked.

---

*[__tests__/components/IconTest.js, line 12 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLP-L_lpCec4Clr5x8a:-KLP-L_lpCec4Clr5x8b:-441886294) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/__tests__/components/IconTest.js#L12)):*
> ```JavaScript
>       <Icon name="classical" title="Mozart" className="pop-icon"/>)
> 
>     // have to check this way since JSX does not work for xlink:href
> ```

I think JSX actually does support xlink:href now, so please try to move the `<use>` tag into the `<svg>` below, like:


```xml
<svg className="Icon-item">
  <use xlink:href="#Icon-classical"/><title>Mozart</title>
</svg>
```

If it fails, then just leave it like it is.

---

*[__tests__/components/SuggestionSourceDetailsTest.js, line 9 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOn071fPWYlVms8R-4:-KLOn071fPWYlVms8R-5:155099252) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/__tests__/components/SuggestionSourceDetailsTest.js#L9)):*
> ```JavaScript
> 
> describe('SuggestionSourceDetailsTest', () => {
>   it('SuggestionSourceDetails markup (imported)', () => {
> ```

We may want to update the test descriptions to make sense with the test function names. Not a big deal for now, but it may lead to better test output. Will have to have a look what the output looks like before we should bother changing it.

e.g. the test code would read a bit better if this were more like `it('should render the expected markup for SuggestionSourceDetails')`, but I don't know if that would give easy-to-understand output when the test is run.

---

*[__tests__/components/TransUnitFilterTest.js, line 158 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOpcHV50HnrsyPmLrd:-KLOpcHV50HnrsyPmLre:722089222) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/__tests__/components/TransUnitFilterTest.js#L158)):*
> ```JavaScript
>     let filterChangeType = 'none'
>     const onFilterChange = statusType => {
>       console.log('clicked', statusType)
> ```

Remove logging.

---

*[app/components/Dropdown/index.js, line 28 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOrjm5YL2qvQw8zIXL:-KLOrjm5YL2qvQw8zIXM:-906459642) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/app/components/Dropdown/index.js#L28)):*
> ```JavaScript
>       const node = this.buttonDiv
>       this.props.onToggle(node)
>     }
> ```

Remove this change. This is not `toggleDropdownIfEnabled()`, and we don't need the check because it doesn't bind it to the click event unless it is enabled (so that check has already been done before it would ever call this).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by davidmason** [comment]
Reviewed 2 of 22 files at r2.
Review status: 22 of 41 files reviewed at latest revision, 6 unresolved discussions.

---

*[__tests__/components/ProgressBarTest.js, line 34 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLP3gtUpwPj8-P60xZu:-KLP3gtUpwPj8-P60xZv:-557056164) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/__tests__/components/ProgressBarTest.js#L34)):*
> ```JavaScript
>         className="Progressbar-item Progressbar-untranslated"
>         style={{ marginLeft: '60%', width: '40%' }}/>
>       </div>
> ```

The spans should be indented by 2 more spaces, not sure what happened there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by davidmason** [comment]
Reviewed 14 of 49 files at r1, 5 of 22 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[package.json, line 110 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLOYva6gbKcRjBBMsJE:-KLPCpC6VmsDkLYk-O8Q:131264769) ([raw file](https://github.com/zanata/zanata-spa/blob/a703af0e0151bc24eb53e02d5017079203ca9712/package.json#L110)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> It is a trade-off either way. I find it more of a hindrance when package.json gets full of too much stuff and it becomes hard to find things in it, but if there are a bunch of different config files it can take a while to learn where each tool is configured from - particularly if the config files have names that are different from the tool.
> 
> Usually you get some benefit from having a separate config because editors and other tools with automatically find the config and use it. This one probably isn't like that since they didn't document it well.
</details>
I think it can remains in there for now unless there's more config coming up. At least not in this pull request.

---

*[__tests__/components/IconTest.js, line 12 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-spa/101#-KLP-L_lpCec4Clr5x8a:-KLPBFU2T-RsuzSW5GxP:-1898057014) ([raw file](https://github.com/zanata/zanata-spa/blob/2dd190727c9da63ea274c582708e6d18259ac426/__tests__/components/IconTest.js#L12)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I think JSX actually does support xlink:href now, so please try to move the `<use>` tag into the `<svg>` below, like:
> 
> 
> ```xml
> <svg className="Icon-item">
>   <use xlink:href="#Icon-classical"/><title>Mozart</title>
> </svg>
> ```
> 
> If it fails, then just leave it like it is.
</details>
Still not supported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by davidmason** [comment]
Reviewed 1 of 50 files at r1, 2 of 6 files at r3.
Review status: 37 of 40 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by davidmason** [comment]
Reviewed 1 of 50 files at r1, 4 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/101)*

**Comment by djansen-redhat** [comment]
Nice lot of tests, looks good :+1:

**Pull request merged**
