### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Updated commands for running Zanata SPA

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-spa/100)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/100)*

**Comment by aeng** [comment]
Merge this after https://github.com/zanata/zanata-spa/tree/react-everything-ZNTA-685 is in master.

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-spa/100#-:-KKkMwLStXJc4KSH3LoS:1417088721)*

**Comment by seanf** [comment]
@aeng @kathryngo We don't need this any more, correct?

**Comment by alex-sl-eng** [comment]
@seanf nope. All in zanata-server now.

**Pull request closed without merging**
