### PR TITLE
migrate: remove all files and migrate to zanata-serve

### PR DESCRIPTION
**Pull request by aeng**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-spa/102)

### CODE REVIEW

**Comment by aeng** [comment]
@seanf Can review this PR?

**Comment by seanf** [comment]
@aeng Did you remove the hidden files, like .travis.yml?

**Comment by aeng** [comment]
@seanf done.

**Comment by seanf** [comment]
:+1: We should also consider deleting all the other branches (beside master).

**Pull request merged**
