### PR TITLE
chore(node): add n to build for consistent node version

### PR DESCRIPTION
**Pull request by davidmason**
n is installed as part of setup so that it can switch to the correct
version of node.

The aim here is to let devs just run `make setup` and not have to worry about how to get _node_ installed and up-to-date.

This does not run n for every build, but that would be easy to add
by adding the "node" target as a dependency of each of the build
targets.

Testing note:

Please check that `make setup` works for you.
- [ ] needs docs to indicate that _n_ is installed. May be better to make _n_ optional with a flag to skip it.

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-spa/96)

### CODE REVIEW

**Comment by davidmason** [comment]
@aeng @lukebrooker can you see if this works for you? Running `make setup` should install *n*, use *n* to set node to version 5.0.0 (because that is in `.node-version`), then do the other setup things that it always used to do.

**Comment by lukebrooker** [comment]
So we are using n instead of nvm? Any reason? As we had already chosen nvm for the front end module in zanata-server.

**Comment by davidmason** [comment]
> we had already chosen nvm for the front end module

I had forgotten or not noticed that. *nvm* should be fine too, and it should be pretty easy to get all the same functionality. I'll change this to use nvm instead.

I think I'll also make sure that all the commands run with nvm so that it will always use the version in .nvmrc so that builds are more repeatable.

**Comment by davidmason** [comment]
Turns out *nvm* is a real pain to get working as part of setup, at least as it is structured. With *n* I could just run the install script and everything just worked afterwards, but with *nvm* it has to run `nvm.sh` - it puts a line in .bashrc (or equivalent) but you have to start a new terminal session to pick it up.

The workaround is to manually source nvm.sh, but you have to do it before every command that uses *nvm* or *npm* since make runs each line of a recipe in a separate shell. I can still make it work, it is just a lot messier.

**Comment by davidmason** [comment]
After some further work trying to get nvm installation happening as part of setup, I have concluded that I am nowhere near good enough with make or shell scripting to make it work within a reasonable time.

The problems:

 1. I don't know how to have `make` conditionally install nvm only when it is not installed. I can do this with other programs that are binaries, but nvm is not like that:
   - the `nvm` command is added to the shell as a *function* (by sourcing `~/.nvm/nvm.sh`)
   - `which` does not find *functions*, so a different method of checking is needed
   - `type -t nvm` and `command -v nvm` will both output something and succeed when nvm has been sourced, and output nothing and fail when nvm has not been sourced
   - make tries some shortcut execution that lacks shell builtins, so trying to capture the output of the above commands in a variable with `HAS_NVM := $(shell type -t nvm)` fails - command "type" is not found.
   - I can add a semicolon `... -t nvm;)` to force make to not do the shortcut execution, but then the command returns nothing
   - I can explicitly tell it the shell to use `$(shell /bin/sh type -t nvm)` but then it returns nothing
 2. `nvm` is made available by sourcing `~/.nvm/nvm.sh` in `~/.bashrc` or equivalent, so either:
   - the developer has to open a completely new shell after nvm is installed before make can use it
   - I would have to source `~/.nvm/nvm.sh` at the start of every command. I can't source it just once before everything since make runs each line of a recipe as a separate shell so the function would be lost before it gets to the next line

With `n` I can just use `which n`, install it if it is missing, and use it immediately in make.

**Comment by lukebrooker** [comment]
I’m fine with this.

**Comment by davidmason** [comment]
> I’m fine with this.

@lukebrooker any part or parts of it in particular?

**Comment by seanf** [comment]
@davidmason Can this be closed?

**Pull request closed without merging**
