### PR TITLE
Use redux and add tests for all React components (ZNTA-71)

### PR DESCRIPTION
**Pull request by davidmason**
For all actions from outside React (i.e. from Angular), actions are dispatched to the single store defined in `editorHeaderDirective`, which provides data to the top level header sections (`EditorHeader`, `NavHeader` and `ControlsHeader`).

Tests all use `retap`, most of them check that the component will render the expected JSX. A few important events are tested, but event testing is not exhaustive at this point. Events should become easier to test when all the internal events are dispatched through the store as well (there is just no need for that at this point).

### Pieces

- *redux*: single store, dispatch actions directly to the store. Uses a pure 'reducer' function to turn previous state + action into new state.
- *react-redux*: wrap the React component tree in a Provider, the connect the top-level components to the state from the redux store.
- *reselect*: memoize state-selector functions so that re-render only happens when the selected state changes (so better performance)
- *retap*: (testing) compare various things between 2 pieces of JSX, for making sure React components render the expected markup.

### Structure

`editorHeaderDirective.js` is where the main redux things happen:

 - The single redux store is created with `createStore(mainReducer, getInitialState())`
   - actually `createStoreWithMiddleware`, see Actions below for that the `thunk` middleware is.
   - `mainReducer` is a pure function that maps from previous `state` and an action to the new `state`.
   - `getInitialState()` just uses the current state from several different angular components.
 - Anything of interest from Angular is tracked with `$watch`, and dispatches an appropriate action to the single redux store.
 - To render, the top level of the React component tree is wrapped with a `<Provider store={store}>`
   - `Provider` comes from module `react-redux`, and is responsible for getting the state from the store to the components

Most of the other redux-y stuff happens in `EditorHeader/index.jsx`, `ControlsHeader/index.jsx` and `NavHeader/index.jsx`.

 - The components near the top of the tree are `connect`ed to the state (from the store), using a selector function that can pull out just the parts of state they need.
   - `connect` comes from `react-redux`, and makes sure the state from the store in the `<Provider>` gets passed into a component's `props`
   - some of them at the moment just select *all* the state - that will change as more of the app is handled by React

Actions are in `actions/index.jsx`, they are basically the same as any flux actions.
Later there will be async actions using `redux-thunk` middleware - it is set up in the architecture, there just aren't any actions that would use it yet.

Reducers: at the moment there is only one (it will be split into a tree of reducers eventually). It is just a big `switch` statement in `reducers/index.jsx`. It uses the `update` React addon as a lightweight alternative to immutablejs. I didn't want to switch to immutablejs just yet because it would make for a messy interface between Angular and React code - better to wait until it is all React and decide then.

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Wrong target branch?  I assume you'll squash merge anyway..

**Comment by davidmason** [comment]
@djansen-redhat this repo does not have the `master`/`integration/master` division. There were no tests for it to pass until now anyway.

I'll look into getting that going for this repo now that there is a way to decide whether to merge it.

**Comment by djansen-redhat** [comment]
Oops my bad

**Comment by davidmason** [comment]
Not all bad though - it reminded me to think about continuous integration in this repo.

**Comment by davidmason** [comment]
fifth-element

**Comment by djansen-redhat** [comment]
- [ ] Not sure if it was working before, but Suggestions manual search keeps showing the current target's results, rather than the searched. (eg. typing "meow" should show no results)

**Comment by davidmason** [comment]
> Not sure if it was working before, but Suggestions manual search keeps showing the current target's results, rather than the searched. (eg. typing "meow" should show no results)

Discussed directly, noting here for posterity:

This is just the hard-coded data in fake-zanata-server, and does not happen when using a real server.

**Comment by davidmason** [comment]
Verified in https://github.com/zanata/zanata-server/pull/1013

**Pull request merged**
